### ISSUE TITLE
Journey to Final Submission

### ISSUE THREAD

**Issue by enreina** [riftadi/trashure#3]
### Login and Registration
- [x] RQ 01: Login System
- [x] RQ 02: Registration System

### Exploration Mode

- [x] RQ 03: Assigning player to an area (task routing)
- [x] RQ 04: Show Street View
- [x] RQ 05: Mini Map (Top-View)
- [x] RQ 06: Spawning Coins 
   - [x] Basic random spawning
   - [x] Improve Spawning (experiment for better gameplay experience)
- [x] RQ 07: Collect coins 
- [x] RQ 08: Collect trash bins 
   - [x] Basic collecting
   - [x] Variate on 'Selection Tool' (see Evaluation #5)
- [x] RQ 09: Score Mechanism
   - [x] Basic Scoring
   - [x] Reward score based on 'verified' trash bin (immediate and delayed score)
- [x] RQ 10: Time Mechanism
   - [x] Basic Time Mechanism
   - [x] Adjust time limit based on area & player experience
- [x] RQ 11: Trophy Room
   - [x] Basic Trophy Room
   - [x]  Mark Verified vs Non-Verified Trophy Room
- [x] RQ 12: High score
- [x] RQ 13: Area Suggestion

### Verification Mode
- [x] RQ 14: Assigning Trash Bin Image
- [x] RQ 15: Verifying Trash Bin

### Admin Dashboard
- [x] RQ 16: Exploration Crowd Working Results Aggregation
- [x] RQ 17: Evaluation Result (see Evaluation section)

## MISC (Miscellaneous Important Stuff Cluster)
The list below are tasks which does not fit into the requirements above (but a part of them somehow).

- [x] MISC 01: Migrate to PostgreSQL (or other RDBMS)
- [x] MISC 02: Deployment (Frontend + Backend)
- [x] MISC 03: Area Database (NZLijn stations area)
- [x] MISC 04: Initial ‘valid’ trash bin data
- [x] MISC 05: Mechanism to Check if Two Trash Bin are the same
- [x] MISC 06: Improve UI/UX & Polishing

## Evaluation
- [x] E 01: RQ, IV, DV, and Experimental Design (see Evaluation #5 )

Ideally we should create a separate issue for each task item, but I would like to know which item each of you are interested to work on, and then we can create the issues for more discussion. I think each task item is explanatory, but if you're in doubt about something, please comment :)

I am not sure if we can accomplish all of these in less than 3 weeks time, but let's try our best 🥇 

@riftadi @nidorano @ger1995 @roynirmal

**Comment by riftadi** [comment]
I'm closing it now as the project is already done. Thanks everyone!
